# Generated by Django 6.0 on 2026-02-17 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pvp', '0001_initial'),
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundStatistics',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number_of_attempts', models.PositiveIntegerField(default=1)),
                ('user_answer', models.TextField(null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_to_solve', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'round_task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='round_statistics',
                        to='pvp.roundtask',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='round_statistics',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'round_statistics',
                'indexes': [
                    models.Index(
                        fields=['user'], name='round_stati_user_id_166b63_idx'
                    ),
                    models.Index(
                        fields=['round_task'], name='round_stati_round_t_869990_idx'
                    ),
                    models.Index(
                        fields=['is_correct'], name='round_stati_is_corr_15eae4_idx'
                    ),
                ],
                'unique_together': {('user', 'round_task')},
            },
        ),
        migrations.CreateModel(
            name='TrainingStatistics',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number_of_attempts', models.PositiveIntegerField(default=1)),
                ('user_answer', models.TextField(null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_to_solve', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'training_task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='statistics',
                        to='trainings.trainingtask',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='training_statistics',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'training_statistics',
                'indexes': [
                    models.Index(
                        fields=['user'], name='training_st_user_id_5dc907_idx'
                    ),
                    models.Index(
                        fields=['training_task'], name='training_st_trainin_2385a7_idx'
                    ),
                    models.Index(
                        fields=['is_correct'], name='training_st_is_corr_1f254c_idx'
                    ),
                ],
                'unique_together': {('user', 'training_task')},
            },
        ),
    ]
