# Generated by Django 6.0 on 2026-01-13 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_statistics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="statistics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="statistics",
            index=models.Index(fields=["user"], name="statistics_user_id_02c963_idx"),
        ),
        migrations.AddIndex(
            model_name="statistics",
            index=models.Index(
                fields=["round_task"], name="statistics_round_t_fcee9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statistics",
            index=models.Index(
                fields=["is_correct"], name="statistics_is_corr_603481_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="statistics",
            unique_together={("user", "round_task")},
        ),
    ]
