# Generated by Django 6.0 on 2026-01-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_statistics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="is_correct",
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="user_answer",
            field=models.TextField(default=None),
        ),
    ]
