# Generated by Django 6.0 on 2026-01-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_statistics", "0003_alter_statistics_is_correct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="is_correct",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="user_answer",
            field=models.TextField(null=True),
        ),
    ]
