# Generated by Django 6.0 on 2026-02-17 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('waiting', 'Waiting'),
                            ('in_progress', 'In progress'),
                            ('finished', 'Finished'),
                            ('technical_error', 'Technical error'),
                        ],
                        default='waiting',
                        max_length=20,
                    ),
                ),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('planed_finish', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'players',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trainings',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trainings_tasks',
                        to='tasks.task',
                    ),
                ),
                (
                    'training',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trainings_tasks',
                        to='trainings.training',
                    ),
                ),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='training',
            name='tasks',
            field=models.ManyToManyField(
                related_name='trainings',
                through='trainings.TrainingTask',
                to='tasks.task',
            ),
        ),
        migrations.AddIndex(
            model_name='trainingtask',
            index=models.Index(
                fields=['training'], name='trainings_t_trainin_614670_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='trainingtask',
            index=models.Index(fields=['task'], name='trainings_t_task_id_a7f910_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingtask',
            unique_together={('training', 'order')},
        ),
    ]
