# Generated by Django 6.0 on 2026-01-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["difficulty"], name="tasks_task_difficu_9292d3_idx"
            ),
        ),
    ]
