# Generated by Django 6.0 on 2026-01-13 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pvp", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_rounds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roundplayer",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="roundplayer",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pvp.round"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="players",
            field=models.ManyToManyField(
                related_name="players",
                through="pvp.RoundPlayer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roundtask",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_tasks",
                to="pvp.round",
            ),
        ),
        migrations.AddField(
            model_name="roundtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_tasks",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="tasks",
            field=models.ManyToManyField(
                related_name="tasks", through="pvp.RoundTask", to="tasks.task"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roundtask",
            unique_together={("round", "order")},
        ),
    ]
