# Generated by Django 6.0 on 2026-01-23 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvp", "0002_initial"),
        ("tasks", "0002_task_tasks_task_difficu_9292d3_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="players",
            field=models.ManyToManyField(
                related_name="rounds",
                through="pvp.RoundPlayer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="tasks",
            field=models.ManyToManyField(
                related_name="rounds", through="pvp.RoundTask", to="tasks.task"
            ),
        ),
        migrations.AddIndex(
            model_name="roundplayer",
            index=models.Index(fields=["round"], name="pvp_roundpl_round_i_2dc1e6_idx"),
        ),
        migrations.AddIndex(
            model_name="roundplayer",
            index=models.Index(
                fields=["player"], name="pvp_roundpl_player__e7334a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roundtask",
            index=models.Index(fields=["round"], name="pvp_roundta_round_i_86902a_idx"),
        ),
        migrations.AddIndex(
            model_name="roundtask",
            index=models.Index(fields=["task"], name="pvp_roundta_task_id_7f1fee_idx"),
        ),
    ]
